#!/bin/sh -e

VERSION=1.0

GREEN='\033[1;32m'
RED='\033[1;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

SYSTEM=$(uname -m)

case "$SYSTEM" in
  x86_64)
    FLAKE_TARGET="x86_64-linux"
    ;;
  aarch64)
    FLAKE_TARGET="aarch64-linux"
    ;;
  *)
    printf "${RED}Unsupported architecture: %s${NC}\n" "$SYSTEM"
    exit 1
    ;;
esac

printf "%sStarting...%s\n" "$YELLOW" "$NC"

# We pass SSH from user to root so root can download secrets from our private Github
sudo SSH_AUTH_SOCK="$SSH_AUTH_SOCK" /run/current-system/sw/bin/nixos-rebuild switch --flake .#$FLAKE_TARGET "$@"

printf "%sSwitch to new generation complete!%s\n" "$GREEN" "$NC"
